language: python

python:
  - '2.6'
  - '2.7'

before_script:
  - mysql -e 'create database test_pymysql;'
  - mysql -e 'create database test_pymysql2;'

script: python -m unittest discover

notifications:
  irc:
    channels: "irc.freenode.org#web2py"
    on_success: change
    on_failure: change
